# Generated by Django 2.2.14 on 2024-11-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20241112_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='paypal_charge_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='stripe_customer_id',
            new_name='paypal_customer_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
