# Generated by Django 2.2.14 on 2024-11-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_newslettersubscriber_question_review_supportticket_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_to_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
