# Generated by Django 2.2.14 on 2024-11-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket', to='core.Item'),
        ),
    ]
