# Generated by Django 2.2.14 on 2024-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_supportticket_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='No Comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
